Repository postmanlabs/postman-docs, pull requests merged in 2021-03, with the labels that each got.

#2879 Add Level Up video as resource for generating code snippets
  src/pages/docs/sending-requests/generate-code-snippets.md
Labels: enhancement

#2887 updated gatsby-plugin-gdpr-cookies version to use latest
  package-lock.json
  package.json
Labels: dependencies

#2918 fixed 302 link; updated contributing doc about links
  CONTRIBUTING.md
  src/pages/docs/administration/upgrading-to-v8.md
Labels: enhancement

#2935 LC Bug: Update conditional for onClickOut function for mobile browsers
  src/components/Header/Header.jsx
Labels: bug

#2938 LC Bug: Update conditional for onClickOut function for mobile browsers v2
  src/components/Header/Header.jsx
Labels: bug
