Repository postmanlabs/postman-docs, pull requests merged in 2023-04, with the labels that each got.

#4675 [TW-1014] Add code reference table style for HTML tables
  src/templates/doc.jsx
  styles/globalStyle.js
Labels: HOLD

#4714 Markeng-2382 NavDropdown & Markeng-2388 footer updates
  build/footerDev.json
  build/navtopicsdropdownDev.json
  src/components/Footer/__snapshots__/Footer.spec.jsx.snap
Labels: HOLD

#4730 update GA to use G4
  bff.js
  gatsby-config.js
Labels: HOLD

#4728 TW-1033 Live Collections April release
  src/pages/docs/collections/live-collections/live-collections-setup.md
Labels: HOLD

#4707 TW-930 Doc JSON comment in API client
  src/pages/docs/sending-requests/requests.md
Labels: RTM

#4722 [TW-1024] pcli publish api version
  src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-versions.md
  src/pages/docs/postman-cli/postman-cli-options.md
Labels: HOLD

#4597 [TW-954] Doc customizable Oauth
  src/pages/docs/sending-requests/authorization.md
Labels: RTM

#4718 TW-1049 Remove guests from the team if they no longer have access to any workspace or collection
  src/pages/docs/administration/managing-your-team/managing-your-team.md
  src/pages/docs/collaborating-in-postman/sharing.md
Labels: RTM

#4720 [TW-1022] Changes to removing/leaving team logic
  src/pages/docs/administration/managing-your-team/managing-your-team.md
  src/pages/docs/administration/sso/admin-sso.md
  src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md
Labels: RTM

#4686 [TW-875] Doc Improvements to Public Documentation
  src/pages/docs/publishing-your-api/publishing-your-docs.md
  src/pages/docs/publishing-your-api/viewing-documentation.md
Labels: HOLD, RTM

#4721 [TW-888] dynamically hide left sidebar
  src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
  src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
  src/pages/docs/getting-started/navigating-postman.md
Labels: HOLD

#4719 TW-1048 Super Admin role assigment changes
  src/pages/docs/administration/managing-your-team/managing-your-team.md
  src/pages/docs/collaborating-in-postman/roles-and-permissions.md
Labels: RTM

#4688 [TW-1004] Add OAS 2.0 support for multi-file and schema docs
  src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
  src/pages/docs/publishing-your-api/documenting-your-api.md
  src/pages/docs/publishing-your-api/viewing-documentation.md
Labels: HOLD, RTM

#4732 [TW-955] Collection overview tab
  src/pages/docs/collaborating-in-postman/public-api-network/organizing-your-workspace.md
  src/pages/docs/collections/collections-overview.md
  src/pages/docs/collections/using-collections.md
  src/pages/docs/getting-started/creating-the-first-collection.md
  src/pages/docs/sending-requests/grpc/grpc-request-interface.md
  src/pages/docs/sending-requests/grpc/using-grpc-examples.md
  src/pages/docs/sending-requests/requests.md
  src/pages/docs/sending-requests/websocket/websocket.md
Labels: RTM

#4712 TW-1056 Add community role updates
  src/pages/docs/collaborating-in-postman/roles-and-permissions.md
Labels: RTM

#4710 [TW-1047] Doc option to stop collection run if an error occurs
  src/pages/docs/collections/running-collections/intro-to-collection-runs.md
Labels: HOLD, RTM

#4689 [TW-1023] Doc sunset of deprecated GitHub and AWS API Gateway integrations
  src/pages/docs/developer/postman-api/intro-api.md
  src/pages/docs/integrations/available-integrations/aws-api-gateway.md
  src/pages/docs/integrations/available-integrations/github.md
Labels: HOLD, RTM
